import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// Every sound effect available to the games.
///
/// The files live in `assets/audio/` and are generated by
/// `generate_game_audio.py` / `generate_audio.py` at the repository root.
enum GameSfx {
  /// Generic soft tick — selections and button presses.
  tap('game_tap.wav', 0.55),

  /// A bubble leaves the launcher.
  shoot('game_shoot.wav', 0.5),

  /// A bubble locks into the grid.
  stick('game_stick.wav', 0.5),

  /// Bubbles / a matched group burst.
  pop('game_pop.wav', 0.55),

  /// Snake picks up food.
  eat('game_eat.wav', 0.6),

  /// Snake hits a wall or itself.
  crash('game_crash.wav', 0.6),

  /// Two candies trade places.
  swap('game_swap.wav', 0.5),

  /// A candy group clears — raise [play] `rate` with the combo count.
  match('game_match.wav', 0.6),

  /// A striped / wrapped / colour-bomb candy detonates.
  blast('game_blast.wav', 0.6),

  /// Candies fall into the gaps after a clear.
  drop('game_drop.wav', 0.45),

  /// A puzzle tile slides into the empty cell.
  slide('game_slide.wav', 0.5),

  /// An illegal move — deliberately soft, never harsh.
  bump('game_bump.wav', 0.45),

  /// A word was spelled correctly.
  correct('game_correct.wav', 0.6),

  /// A word was spelled wrongly.
  wrong('game_wrong.wav', 0.5),

  /// Progressed to the next level.
  levelUp('game_levelup.wav', 0.6),

  /// A level or stage was cleared.
  win('game_win.wav', 0.65),

  /// Out of moves, shots or lives.
  lose('game_lose.wav', 0.6);

  const GameSfx(this.file, this.volume);

  /// File name inside `assets/audio/`.
  final String file;

  /// Base playback volume for this effect.
  final double volume;
}

/// Plays the game's sound effects through a small pool of pre-loaded
/// [AudioPlayer]s.
///
/// SFX are short and fire in bursts (a swap plus its clear, a cascade of
/// matches), so this keeps [GameSfx.poolSize] players warm per effect and
/// round-robins between them. That keeps latency low without re-decoding the
/// asset on every call, and lets overlapping effects still be heard.
///
/// Every method is fire-and-forget and swallows platform errors — a game must
/// never fail to play because a sound could not be decoded.
class GameAudio {
  GameAudio._();

  static final GameAudio instance = GameAudio._();

  /// Players kept warm per effect, so a burst of sounds can overlap.
  static const int poolSize = 3;

  /// Ignore repeat calls of the same effect that arrive within this window.
  /// Stops rapid-fire events (tile slides, cascades) from turning into mush.
  static const Duration _throttle = Duration(milliseconds: 60);

  static final AudioContext _context = AudioContext(
    android: AudioContextAndroid(
      contentType: AndroidContentType.sonification,
      usageType: AndroidUsageType.game,
      // Duck other audio instead of taking focus, so calm music keeps playing
      // underneath the effects.
      audioFocus: AndroidAudioFocus.gainTransientMayDuck,
    ),
  );

  final Map<GameSfx, List<AudioPlayer>> _pools = {};
  final Map<GameSfx, int> _cursors = {};
  final Map<GameSfx, DateTime> _lastPlayed = {};
  final Set<GameSfx> _loading = {};

  bool _enabled = true;
  bool _unavailable = false;

  /// Whether effects are audible. Toggled from the games hub.
  final ValueNotifier<bool> enabled = ValueNotifier<bool>(true);

  bool get isEnabled => _enabled && !_unavailable;

  /// Silences (or restores) every effect and stops anything still playing.
  void setEnabled(bool value) {
    if (_enabled == value) return;
    _enabled = value;
    enabled.value = value;
    if (!value) unawaited(stop());
  }

  /// Plays [sfx]. Safe to call from anywhere, including after `dispose()`.
  ///
  /// [rate] shifts the pitch — handy for reward-scaling feedback such as
  /// Candy Crush combos. [volume] multiplies the effect's base volume.
  void play(GameSfx sfx, {double rate = 1.0, double? volume}) {
    if (!isEnabled) return;

    final now = DateTime.now();
    final last = _lastPlayed[sfx];
    if (last != null && now.difference(last) < _throttle) return;
    _lastPlayed[sfx] = now;

    unawaited(_play(sfx, rate, volume ?? sfx.volume));
  }

  Future<void> _play(GameSfx sfx, double rate, double volume) async {
    try {
      final players = await _poolFor(sfx);
      if (players.isEmpty) return;
      final player = players[_nextIndex(sfx)];
      // Re-check: the user may have muted while the pool was loading.
      if (!isEnabled) return;
      await player.stop();
      await player.setVolume(volume);
      await player.setPlaybackRate(rate);
      await player.resume();
    } catch (_) {
      // Sound is a nice-to-have; never surface playback failures to a game.
    }
  }

  Future<List<AudioPlayer>> _poolFor(GameSfx sfx) async {
    final existing = _pools[sfx];
    if (existing != null) return existing;
    if (_unavailable) return const [];
    // Guard against concurrent callers all building the same pool.
    if (!_loading.add(sfx)) return _pools[sfx] ?? const [];

    final players = <AudioPlayer>[];
    try {
      for (var i = 0; i < poolSize; i++) {
        final player = AudioPlayer(playerId: 'sfx_${sfx.name}_$i');
        players.add(player);
        await player.setReleaseMode(ReleaseMode.stop);
        await player.setAudioContext(_context);
        await player.setPlayerMode(PlayerMode.mediaPlayer);
        await player.setSource(AssetSource('audio/${sfx.file}'));
      }
      return _pools[sfx] = players;
    } catch (_) {
      // A missing or corrupt asset disables sound rather than spamming errors.
      _unavailable = true;
      for (final player in players) {
        try {
          await player.dispose();
        } catch (_) {}
      }
      return const [];
    } finally {
      _loading.remove(sfx);
    }
  }

  /// Round-robin index into a pool so overlapping effects each get a player.
  int _nextIndex(GameSfx sfx) {
    final players = _pools[sfx];
    if (players == null) return 0;
    final next = ((_cursors[sfx] ?? 0) + 1) % players.length;
    _cursors[sfx] = next;
    return next;
  }

  /// Stops every playing effect without unloading the pools.
  Future<void> stop() async {
    for (final players in _pools.values) {
      for (final player in players) {
        try {
          await player.stop();
        } catch (_) {}
      }
    }
  }

  /// Releases every player. Call when the app is shutting down for good.
  Future<void> dispose() async {
    final players = [for (final p in _pools.values) ...p];
    _pools.clear();
    _cursors.clear();
    _lastPlayed.clear();
    for (final player in players) {
      try {
        await player.dispose();
      } catch (_) {}
    }
  }
}
