// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkigTbhb6ralBn0YqhElygUkHxpWigA28',
    appId: '1:384910835517:web:9b7915f82dd2ff4299cf54',
    messagingSenderId: '384910835517',
    projectId: 'mine-care',
    authDomain: 'mine-care.firebaseapp.com',
    storageBucket: 'mine-care.firebasestorage.app',
    measurementId: 'G-TZ4YXMZHE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYNJVzAfVul8EAi0Cw8EVp4YUbD8Y7EEA',
    appId: '1:384910835517:android:3df2d6d3225dd6dd99cf54',
    messagingSenderId: '384910835517',
    projectId: 'mine-care',
    storageBucket: 'mine-care.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRu9aOp-Zb_B0ulrG96SyGW1LxZIt8BZA',
    appId: '1:384910835517:ios:d715e998d983d20499cf54',
    messagingSenderId: '384910835517',
    projectId: 'mine-care',
    storageBucket: 'mine-care.firebasestorage.app',
    iosClientId: '384910835517-qu8q4u53dnt0ds2kgmuakdsqmath6e9n.apps.googleusercontent.com',
    iosBundleId: 'com.mindcare.mindCareApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRu9aOp-Zb_B0ulrG96SyGW1LxZIt8BZA',
    appId: '1:384910835517:ios:d715e998d983d20499cf54',
    messagingSenderId: '384910835517',
    projectId: 'mine-care',
    storageBucket: 'mine-care.firebasestorage.app',
    iosClientId: '384910835517-qu8q4u53dnt0ds2kgmuakdsqmath6e9n.apps.googleusercontent.com',
    iosBundleId: 'com.mindcare.mindCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkigTbhb6ralBn0YqhElygUkHxpWigA28',
    appId: '1:384910835517:web:3c592a35dafa496099cf54',
    messagingSenderId: '384910835517',
    projectId: 'mine-care',
    authDomain: 'mine-care.firebaseapp.com',
    storageBucket: 'mine-care.firebasestorage.app',
    measurementId: 'G-6X1TFFE8ZR',
  );
}
